#!/usr/bin/perl

# Esto incluye el archivo buffer.pl que contiene la funcion get
do 'buffer.pl';

my $item, $cnt, $max, $lin, @arr;
if ($#ARGV != 0 ) {
  die "uso: put <item>\n";
}
$item=$ARGV[0];
my $monitor= "/dev/monitor";
if (exists $ENV{'DEVMON'}) {
  $monitor= $ENV{'DEVMON'};
}

put($monitor, $item);

